### ISSUE TITLE
Fix logodisplay in winners view

### ISSUE THREAD

**Issue by nivekcode** [nivekcode/Footradamus-old#81]
Teilweise wird das logo bei der Anzeige des Gewinners nicht angezeigt. Bei folgenden Teams erscheint die Winner Anzeige nicht richtig:

Bundesliga:
- Bayern München / https://intense-bastion-56637.herokuapp.com/bundesliga/bayern-m%C3%BCnchen.png
- Mainz 05 / https://intense-bastion-56637.herokuapp.com/bundesliga/mainz-05.png
- Herta Berlin / https://intense-bastion-56637.herokuapp.com/bundesliga/hertha-bsc.png
- Köln / https://intense-bastion-56637.herokuapp.com/bundesliga/k%C3%B6ln.png
- Schalke / https://intense-bastion-56637.herokuapp.com/bundesliga/schalke-04.png
- Borussia M. Gladbach / https://intense-bastion-56637.herokuapp.com/bundesliga/borussia-m'gladbach.png

Premier League:
- Swansea / https://intense-bastion-56637.herokuapp.com/premier-league/swansea-city.png
- Bournemouth / https://intense-bastion-56637.herokuapp.com/premier-league/afc-bournemouth.png

Primera Division:
- Malaga / https://intense-bastion-56637.herokuapp.com/primera-division/m%C3%A1laga.png
- Atletico / https://intense-bastion-56637.herokuapp.com/primera-division/atl%C3%A9tico-madrid.png

**Comment by kreuzerk** [comment]
Bayern München - https://intense-bastion-56637.herokuapp.com/bundesliga/bayern-m%C3%BCnchen.png
